# Generated by Django 4.1.1 on 2022-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='foto',
            field=models.ImageField(upload_to='./media/carPhotos'),
        ),
    ]
