# Generated by Django 4.1.1 on 2022-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_alter_carro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='foto',
            field=models.ImageField(null=True, upload_to='carPhotos/'),
        ),
    ]
